### ISSUE TITLE
The posts should show the writing datetime.

### ISSUE THREAD

**Issue by bugtender** [deduce/til#1]
Hi, Lawrence

I found that your blog posts show the **hexo generate datetime** instead of **writing datetime**.

<img width="575" alt="screen shot 2017-05-05 at 2 15 48 am" src="https://cloud.githubusercontent.com/assets/5573816/25718486/dffa7896-3138-11e7-98f6-13389428bb2f.png">

Maybe add date tag in the head of markdown file will correct it. [doc](https://hexo.io/zh-tw/docs/front-matter.html)

**Comment by deduce** [comment]
@bugtender sweet! I didn't notice that problem when I tried to fix the ``sed`` problem.
